name: Self Approve

on:
  pull_request:
    branches:
      - master

jobs:
  approve:
    if: github.actor == 'oognuyh'
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.TOKEN }}
          number: ${{ github.event.number }}

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
