name: Reformat

on:
  pull_request:
    branches:
      - feature/*

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd BOJ2480 && ls -al
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          githubToken: ${{ secrets.TOKEN }}
          commitMessage: "reformat"
