name: Reformat

on:
  pull_request:
    branches:
      - feature/*

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - run: cd BOJ2480 && ls -al

      - name: Reformat java files
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          githubToken: ${{ secrets.TOKEN }}
          commitMessage: "reformat java files"

      - run: git status
