name: Reformat

on:
  pull_request:
    branches:
      - feature/*

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - run: cd BOJ2480 && ls -al
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          githubToken: ${{ secrets.TOKEN }}
          commitMessage: "reformat java files"
      - run: git status
